package uns.ac.rs.controller.events;

public enum NotificationType {
    RESERVATION_REQUEST_CREATED,
    RESERVATION_DECLINED,
    PERSONAL_REVIEW,
    ACCOMMODATION_REVIEW,
    RESERVATION_REQUEST_RESOLVED
}